import {data,save,week,cat} from './storage.js';import {monday,current,key,past,fmt} from './weeks.js';import {initSchedule,renderSchedule,unlinkSchedule} from './schedule.js';import {initBackup} from './backup.js';
let selected=current();const $=x=>document.getElementById(x);const palette=['#c9efd7','#f7c6cb','#c6def5','#f7dda5','#d8cdf5','#f3c5e5','#bfe4df','#f5c6ad','#d8e9b9','#c8d5f5','#eed0a8','#c9e7f0','#e6c6f2','#f0d4d4','#cde5c0','#d5d2f0','#f4e0b8','#bddbd1','#e5c4b4','#c7d9ec','#d9e5bd','#e7cce2','#c6e1dc','#f0c8b8','#d5e0f2','#ead8af','#c9d9c0','#dfc8ee','#bcd8e5','#edcbd1','#d8e6c8','#f0d3b4','#c8c9e9','#c4e0d3','#e8c6da','#d7dfb5','#c9d7ef','#f0c9c1','#d6c7e8','#c2e2e2','#e8d0ba','#c9e0c1','#e2c8d8','#c7d4df','#eee0b7','#c8e4d8','#e5c9bf','#d2d7ef','#d8e1c0','#e3cee8'];
function modal(title,fields,buttons){$('modalTitle').textContent=title;$('modalFields').innerHTML=fields;$('modalActions').innerHTML=buttons;$('modalError').textContent='';$('modal').classList.add('show')}export const close=()=> $('modal').classList.remove('show');export const getDate=()=>selected;
function icon(t,fn){const b=document.createElement('button');b.className='icon';b.textContent=t;b.onclick=fn;return b}
function renderPriorities(lock){const w=week(key(selected)),el=$('priorityList');el.innerHTML='';w.priorities.forEach((p,i)=>{const c=cat(p.id);if(!c)return;const r=document.createElement('div');r.className='row';const n=document.createElement('div');n.className='cell';n.style.background=c.color;n.textContent=c.title;r.append(n);if(!lock){r.append(icon('✎',()=>editPriority(c)),icon('×',()=>{w.priorities.splice(i,1);w.goals.forEach(g=>{if(g.priorityId===p.id)g.priorityId=null});unlinkSchedule(w,p.id);save();render()}))}el.append(r)});$('addPriority').style.display=lock||w.priorities.length>=4?'none':'block'}
function addPriority(){modal('Add priority','<div class="field"><label>Category name</label><input id="ftext"></div>','<button id="cancel">Cancel</button><button class="primary" id="ok">Add priority</button>');$('cancel').onclick=close;$('ok').onclick=()=>{const t=$('ftext').value;if(!t)return $('modalError').textContent='Enter a category name.';const w=week(key(selected));let c=data.categories.find(x=>x.title===t);if(c&&w.priorities.some(x=>x.id===c.id))return $('modalError').textContent='This priority is already in this week.';if(!c){c={id:'c'+Date.now(),title:t,color:palette[data.categories.length%palette.length]};data.categories.push(c)}w.priorities.push({id:c.id});save();close();render()}}
function editPriority(c){modal('Edit category','<div class="field"><label>Category name</label><input id="ftext"></div>','<button id="cancel">Cancel</button><button class="primary" id="ok">Save</button>');$('ftext').value=c.title;$('cancel').onclick=close;$('ok').onclick=()=>{if(!$('ftext').value)return;c.title=$('ftext').value;save();close();render()}}
function renderNext(lock){const w=week(key(selected)),el=$('nextList');el.innerHTML='';w.nextWeek.forEach((x,i)=>{const r=document.createElement('div');r.className='row';const n=document.createElement('div');n.className='cell';n.textContent=x.text;r.append(n);if(!lock)r.append(icon('✎',()=>nextPopup(i)),icon('×',()=>{w.nextWeek.splice(i,1);save();render()}));el.append(r)});$('addNext').style.display=lock?'none':'block'}
function nextPopup(i=null){const w=week(key(selected));modal(i===null?'Add to Next Week':'Edit Next Week item','<div class="field"><label>Next Week item</label><input id="ftext"></div>','<button id="cancel">Cancel</button><button class="primary" id="ok">Save</button>');if(i!==null)$('ftext').value=w.nextWeek[i].text;$('cancel').onclick=close;$('ok').onclick=()=>{if(!$('ftext').value)return $('modalError').textContent='Enter a Next Week item.';if(i===null)w.nextWeek.push({text:$('ftext').value});else w.nextWeek[i].text=$('ftext').value;save();close();render()}}
function renderGoals(lock){const w=week(key(selected)),el=$('goalList');el.innerHTML='';w.goals.forEach((g,i)=>{const c=cat(g.priorityId),r=document.createElement('div');r.className='row goalrow';const n=document.createElement('div');n.className='cell';n.textContent=g.text;n.style.background=c?c.color:'#f1f2f4';r.append(n);if(lock){const s=document.createElement('div');s.textContent=g.status;r.append(s)}else{const s=document.createElement('select');s.className='status';['To Do','Not Done','Partially Done','Done'].forEach(v=>s.add(new Option(v,v,v===g.status,v===g.status)));s.onchange=()=>{g.status=s.value;save()};r.append(s,icon('✎',()=>goalPopup(i)),icon('×',()=>{w.goals.splice(i,1);save();render()}))}el.append(r)});$('addGoal').style.display=lock?'none':'block'}
function goalPopup(i=null){const w=week(key(selected));let opts='<option value="">No priority</option>'+w.priorities.map(p=>`<option value="${p.id}">${cat(p.id)?.title||''}</option>`).join('');modal(i===null?'Add goal':'Edit goal',`<div class="field"><label>Goal</label><input id="ftext"></div><div class="field"><label>Linked priority (optional)</label><select id="fpriority">${opts}</select></div>`,'<button id="cancel">Cancel</button><button class="primary" id="ok">Save</button>');if(i!==null){$('ftext').value=w.goals[i].text;$('fpriority').value=w.goals[i].priorityId||''}$('cancel').onclick=close;$('ok').onclick=()=>{if(!$('ftext').value)return $('modalError').textContent='Enter a goal.';if(i===null)w.goals.push({text:$('ftext').value,status:'To Do',priorityId:$('fpriority').value||null});else Object.assign(w.goals[i],{text:$('ftext').value,priorityId:$('fpriority').value||null});save();close();render()}}
function render(){const end=new Date(selected);end.setDate(end.getDate()+6);$('weekLabel').textContent=fmt(selected)+' – '+fmt(end)+' '+end.getFullYear();const lock=past(selected);renderPriorities(lock);renderNext(lock);renderGoals(lock);renderSchedule(selected,lock);save()}
$('addPriority').onclick=addPriority;$('addNext').onclick=()=>nextPopup();$('addGoal').onclick=()=>goalPopup();$('prev').onclick=()=>{selected=new Date(selected);selected.setDate(selected.getDate()-7);render()};$('next').onclick=()=>{selected=new Date(selected);selected.setDate(selected.getDate()+7);render()};$('today').onclick=()=>{selected=current();render()};$('modal').onclick=e=>{if(e.target===e.currentTarget)close()};initSchedule(getDate,render,modal,close);initBackup({goCurrent:()=>{selected=current()},rerender:render,show:modal,hide:close});render();