const PALETTE=['#c9efd7','#f7c6cb','#c6def5','#f7dda5','#d8cdf5','#f3c5e5','#bfe4df','#f5c6ad','#d8e9b9','#c8d5f5','#eed0a8','#c9e7f0','#e6c6f2','#f0d4d4','#cde5c0','#d5d2f0','#f4e0b8','#bddbd1','#e5c4b4','#c7d9ec','#d9e5bd','#e7cce2','#c6e1dc','#f0c8b8','#d5e0f2','#ead8af','#c9d9c0','#dfc8ee','#bcd8e5','#edcbd1','#d8e6c8','#f0d3b4','#c8c9e9','#c4e0d3','#e8c6da','#d7dfb5','#c9d7ef','#f0c9c1','#d6c7e8','#c2e2e2','#e8d0ba','#c9e0c1','#e2c8d8','#c7d4df','#eee0b7','#c8e4d8','#e5c9bf','#d2d7ef','#d8e1c0','#e3cee8'];
function category(id){return data.categories.find(c=>c.id===id)}
function displayCategory(item){return item.snapshot||category(item.id)}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function freezePastUses(id,title,color){Object.entries(data.weeks).forEach(([wk,w])=>{if(new Date(wk+'T00:00:00')<currentStart())ensureWeekShape(w).priorities.forEach(it=>{if(it.id===id&&!it.snapshot)it.snapshot={title,color}})})}
function renderPriorities(){let week=getWeekData(selected).priorities,locked=isPast(),list=document.getElementById('priorityList');list.innerHTML='';document.getElementById('count').innerHTML=locked?'<span class="locked">Locked</span>':week.length+' / 4';document.getElementById('prioritySub').textContent=locked?'This week is locked and cannot be changed.':'Choose up to 4 main priorities for this week.';week.forEach((item,i)=>{let c=displayCategory(item);if(!c)return;let row=document.createElement('div');row.className='priority-row';row.innerHTML='<div class="priority-name" style="background:'+c.color+'">'+escapeHtml(c.title)+'</div>'+(locked?'':'<button class="icon-btn edit" title="Rename category">✎</button><button class="icon-btn remove" title="Remove from this week">×</button>');if(!locked){row.querySelector('.edit').onclick=()=>openPriorityEdit(item.id);row.querySelector('.remove').onclick=()=>{week.splice(i,1);saveData();renderPriorities()}}list.appendChild(row)});let add=document.getElementById('addPriorityBtn');add.style.display=locked?'none':'block';add.disabled=week.length>=4}
function openPriorityAdd(){openPlannerModal({type:'priorityAdd',title:'Add priority',label:'Category name',value:'',placeholder:'e.g. HMI, Team, Pipeline',button:'Add priority'})}
function openPriorityEdit(id){let c=category(id);openPlannerModal({type:'priorityEdit',id,title:'Edit category',label:'Category name',value:c.title,placeholder:'',button:'Save'})}
function submitPriority(mode){let title=modalInput.value;if(!title){showModalError('Enter a category name.');return}if(mode.type==='priorityEdit'){let c=category(mode.id);freezePastUses(c.id,c.title,c.color);c.title=title;saveData();closePlannerModal();renderAll();return}let week=getWeekData(selected).priorities;if(week.length>=4)return;let c=data.categories.find(x=>x.title===title);if(c&&week.some(x=>x.id===c.id)){showModalError('This priority is already in this week.');return}if(!c){let used=new Set(data.categories.map(x=>x.color));let color=PALETTE.find(x=>!used.has(x))||PALETTE[data.categories.length%PALETTE.length];c={id:'c'+Date.now()+Math.random().toString(16).slice(2),title,color};data.categories.push(c)}week.push({id:c.id});saveData();closePlannerModal();renderAll()}
