import {save,week,cat} from './storage.js';import {key} from './weeks.js';const $=x=>document.getElementById(x),D=['Monday','Tuesday','Wednesday','Thursday','Friday'],MEET='#53657D';let getDate,rerender,show,hide,edit=null;
const mins=t=>{let[a,b]=t.split(':').map(Number);return a*60+b},dur=x=>mins(x.end)-mins(x.start);function times(){let a=[];for(let m=540;m<=1020;m+=30)a.push(String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0'));return a}
export function unlinkSchedule(w,id){w.schedule.forEach(x=>{if(x.type==='priority'&&x.priorityId===id){x.type='none';x.priorityId=null}})}
export function initSchedule(g,r,m,c){getDate=g;rerender=r;show=m;hide=c;$('addSchedule').onclick=()=>popup()}
function typeName(x){if(x.type==='meeting')return'Meeting';if(x.type==='none')return'No priority';return cat(x.priorityId)?.title||'No priority'}
function displayBlock(b,x){const n=typeName(x),d=dur(x);b.innerHTML='';const t=document.createElement('span');t.className='block-type';t.textContent=d===30?(n[0]||'N').toUpperCase():n;b.append(t);if(d>=90&&x.label){const l=document.createElement('span');l.className='block-label';l.textContent=x.label;b.append(l)}}
function colour(x){return x.type==='meeting'?MEET:x.type==='priority'?(cat(x.priorityId)?.color||'#f1f2f4'):'#f1f2f4'}
export function renderSchedule(date,locked){let scale=$('scale');scale.innerHTML='';for(let h=9;h<=17;h++){let s=document.createElement('span');s.textContent=String(h).padStart(2,'0')+':00';s.style.left=((h-9)/8*100)+'%';if(h===9)s.style.transform='none';if(h===17)s.style.transform='translateX(-100%)';scale.append(s)}let w=week(key(date)),body=$('scheduleBody');body.innerHTML='';D.forEach(day=>{let row=document.createElement('div');row.className='schedrow';let dl=document.createElement('div');dl.className='day';dl.textContent=day;let tr=document.createElement('div');tr.className='track';let l=document.createElement('div');l.className='lunch';l.textContent='Lunch';tr.append(l);w.schedule.filter(x=>x.day===day).forEach(x=>{let b=document.createElement('button');b.className='block';displayBlock(b,x);b.style.background=colour(x);b.style.color=x.type==='meeting'?'white':'#182033';b.style.left=((mins(x.start)-540)/480*100)+'%';b.style.width=(dur(x)/480*100)+'%';b.title=x.start+' to '+x.end+(x.label?' · '+x.label:'');if(locked)b.disabled=true;else b.onclick=()=>popup(x.id);tr.append(b)});row.append(dl,tr);body.append(row)});$('addSchedule').style.display=locked?'none':'block'}
function popup(id=null){edit=id;let w=week(key(getDate())),x=id?w.schedule.find(a=>a.id===id):null;let types='<option value="meeting">Meeting</option><option value="none">No priority</option>'+w.priorities.map(p=>`<option value="priority:${p.id}">${cat(p.id)?.title||''}</option>`).join('');let ts=times().map(t=>`<option>${t}</option>`).join('');show(id?'Edit Schedule Item':'Add Schedule Item',`<div class="field"><label>Day</label><select id="sday">${D.map(d=>`<option>${d}</option>`).join('')}</select></div><div class="field"><label>Start</label><select id="sstart">${ts}</select></div><div class="field"><label>End</label><select id="send">${ts}</select></div><div class="field"><label>Type</label><select id="stype">${types}</select></div><div class="field"><label>Label (optional)</label><input id="slabel" type="text"></div>`,`${id?'<button class="danger" id="remove">Remove</button>':''}<button id="cancel">Cancel</button><button class="primary" id="ok">${id?'Save changes':'Add item'}</button>`);if(x){$('stype').value=x.type==='priority'?'priority:'+x.priorityId:x.type;$('sday').value=x.day;$('sstart').value=x.start;$('send').value=x.end;$('slabel').value=x.label||''}else{$('sday').value='Monday';$('sstart').value='09:00';$('send').value='09:30'}$('cancel').onclick=hide;$('ok').onclick=submit;if(id)$('remove').onclick=()=>{w.schedule=w.schedule.filter(a=>a.id!==id);save();hide();rerender()}}
function submit(){let w=week(key(getDate())),v=$('stype').value,c={type:v.startsWith('priority:')?'priority':v,priorityId:v.startsWith('priority:')?v.slice(9):null,day:$('sday').value,start:$('sstart').value,end:$('send').value,label:$('slabel').value.trim()};if(mins(c.end)<=mins(c.start))return $('modalError').textContent='End time must be later than start time.';let overlap=w.schedule.some(x=>x.id!==edit&&x.day===c.day&&mins(c.start)<mins(x.end)&&mins(c.end)>mins(x.start));if(overlap)return $('modalError').textContent='This time is already occupied.';if(edit)Object.assign(w.schedule.find(x=>x.id===edit),c);else w.schedule.push({id:'s'+Date.now(),...c});save();hide();rerender()}